using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Wasp.AspNetCore.SourceGenerator;

// Roslyn incremental source generator for Wasp.AspNetCore consumers.
//
// What it does today (M1.3 / #50): scans the consumer's compilation for
// IEndpointRouteBuilder.MapGet / MapPost / MapPut / MapDelete / MapPatch
// invocations and emits a `WaspEndpointMap` partial helper class containing
// a const string `Manifest` listing every detected route. The intent is
// twofold:
//
//   1. Prove the generator infrastructure is wired correctly (the official
//      .NET 10 Microsoft.AspNetCore.Http.RequestDelegateGenerator already
//      emits the actual delegate metadata; we don't compete with it).
//   2. Give the canister author a build-time assertion that their endpoints
//      were seen by the generator pipeline — useful for catching trim-away
//      regressions in M2/M3 when more middleware enters the picture.
//
// Future scope (post-M2): emit a JsonSerializerContext partial that aggregates
// every return type and body-binding parameter type seen in Map* calls, so
// users don't have to maintain a hand-written JsonSerializerContext as they
// add endpoints. Rough plan in NOTES at the bottom of this file.

[Generator]
public sealed class EndpointDiagnosticsGenerator : IIncrementalGenerator
{
    private static readonly string[] MapMethodNames =
    {
        "MapGet", "MapPost", "MapPut", "MapDelete", "MapPatch",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var endpoints = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsMapInvocation(node),
                transform: static (ctx, _) => Match(ctx))
            .Where(static m => m is not null);

        var combined = context.CompilationProvider.Combine(endpoints.Collect());
        context.RegisterSourceOutput(combined, static (spc, source) => Emit(spc, source.Right!));
    }

    private static bool IsMapInvocation(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv) return false;
        if (inv.Expression is not MemberAccessExpressionSyntax member) return false;
        var name = member.Name.Identifier.Text;
        for (int i = 0; i < MapMethodNames.Length; i++)
        {
            if (MapMethodNames[i] == name) return true;
        }
        return false;
    }

    private static MatchedEndpoint? Match(GeneratorSyntaxContext ctx)
    {
        var inv = (InvocationExpressionSyntax)ctx.Node;
        var member = (MemberAccessExpressionSyntax)inv.Expression;
        var symbol = ctx.SemanticModel.GetSymbolInfo(inv).Symbol as IMethodSymbol;
        if (symbol is null) return null;

        // Only match overloads that target IEndpointRouteBuilder (the
        // ASP.NET Core extension methods, not arbitrary user MapGet calls).
        var receiverType = symbol.IsExtensionMethod
            ? symbol.Parameters.FirstOrDefault()?.Type
            : symbol.ReceiverType;
        if (receiverType is null) return null;
        bool isEndpointRouteBuilder = false;
        if (receiverType.ToDisplayString() == "Microsoft.AspNetCore.Routing.IEndpointRouteBuilder")
            isEndpointRouteBuilder = true;
        foreach (var iface in receiverType.AllInterfaces)
        {
            if (iface.ToDisplayString() == "Microsoft.AspNetCore.Routing.IEndpointRouteBuilder")
            {
                isEndpointRouteBuilder = true;
                break;
            }
        }
        if (!isEndpointRouteBuilder) return null;

        // Extract the route pattern (first arg, must be a string literal for
        // us to record it; otherwise skip).
        if (inv.ArgumentList.Arguments.Count < 1) return null;
        var firstArg = inv.ArgumentList.Arguments[0].Expression;
        string? route = null;
        if (firstArg is LiteralExpressionSyntax { Token: { ValueText: var s } })
        {
            route = s;
        }

        return new MatchedEndpoint(member.Name.Identifier.Text, route ?? "(non-literal)");
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<MatchedEndpoint?> endpoints)
    {
        var seen = endpoints
            .Where(e => e is not null)
            .Select(e => $"{e!.Method,-7} {e.Route}")
            .OrderBy(s => s, System.StringComparer.Ordinal)
            .Distinct()
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> emitted by Wasp.AspNetCore.SourceGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Wasp.AspNetCore.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Build-time list of every IEndpointRouteBuilder.Map* call detected in");
        sb.AppendLine("/// the consumer compilation. Surfaces via");
        sb.AppendLine("/// <c>Wasp.AspNetCore.Generated.WaspEndpointMap.Manifest</c> so canister");
        sb.AppendLine("/// authors can assert the expected routes are present at build time.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class WaspEndpointMap");
        sb.AppendLine("{");
        sb.Append("    public const int Count = ").Append(seen.Length).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    public const string Manifest = ");
        if (seen.Length == 0)
        {
            sb.AppendLine("        \"(no MapGet/MapPost/MapPut/MapDelete/MapPatch calls detected)\";");
        }
        else
        {
            for (int i = 0; i < seen.Length; i++)
            {
                bool last = i == seen.Length - 1;
                sb.Append("        \"")
                  .Append(seen[i].Replace("\\", "\\\\").Replace("\"", "\\\""))
                  .Append(last ? "\";" : "\\n\" +")
                  .AppendLine();
            }
        }
        sb.AppendLine("}");

        spc.AddSource("WaspEndpointMap.g.cs", sb.ToString());
    }

    private sealed class MatchedEndpoint
    {
        public MatchedEndpoint(string method, string route)
        {
            Method = method;
            Route = route;
        }
        public string Method { get; }
        public string Route { get; }
    }
}

// NOTES — future expansion (defer to post-M2)
//
// JsonSerializerContext aggregation:
//   * Walk each Map* invocation a second time, this time inspecting the
//     handler argument's symbol (lambda or method group).
//   * Collect the IMethodSymbol return type; if it's
//     Task<T>/ValueTask<T>/IResult, unwrap.
//   * Collect any non-route, non-route-pattern, non-service parameter type
//     (= body-bound or query-bound).
//   * Emit a `partial class WaspGeneratedJsonContext : JsonSerializerContext`
//     with a [JsonSerializable] attribute per unique non-primitive,
//     non-string, non-IResult type.
//   * Generate a service-collection extension to register it in the
//     JsonOptions chain.
//
// Endpoint analyzer warnings:
//   * Warn (e.g. WAS001) when a Map* handler returns an anonymous type without
//     a registered JsonSerializerContext — the official RDG silently fails
//     trim with a CS error, our analyzer would catch it earlier.
//   * Warn (WAS002) when a Map* handler awaits an unsupported API
//     (Task.Delay, Task.Run, Console.WriteLine) — see Wasp.AspNetCore
//     UNSUPPORTED.md.
