<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>WaspBlazor.EmitVectors</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Wasp.AspNetCore.Blazor.Server/Wasp.AspNetCore.Blazor.Server.csproj" />
  </ItemGroup>
</Project>
