namespace Wasp.IcCdk.SourceGenerator;

// Attribute source emitted into every consuming project at build time.
// Lives in the generator (not in Wasp.IcCdk.dll) so users get the
// attribute even in scenarios where the DLL isn't loaded yet (e.g.
// during the source-generation pass itself).
internal static class AttributeSource
{
    public const string Hint = "Wasp.IcCdk.Attributes.g.cs";

    public const string Source = """
        // <auto-generated/> emitted by Wasp.IcCdk.SourceGenerator
        namespace Wasp.IcCdk;

        // Set Manual=true to skip auto Candid arg decoding + auto reply
        // (use this when the method replies later from a callback, e.g.
        // an HTTPS outcall). The user's method must be parameterless and
        // void; they call MessageContext.ArgData / Reply.Bytes themselves.

        [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
        public sealed class CanisterQueryAttribute : System.Attribute
        {
            public CanisterQueryAttribute(string? name = null) { Name = name; }
            public string? Name { get; }
            public bool Manual { get; set; }
        }

        [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
        public sealed class CanisterUpdateAttribute : System.Attribute
        {
            public CanisterUpdateAttribute(string? name = null) { Name = name; }
            public string? Name { get; }
            public bool Manual { get; set; }
        }

        [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
        public sealed class CanisterCompositeQueryAttribute : System.Attribute
        {
            public CanisterCompositeQueryAttribute(string? name = null) { Name = name; }
            public string? Name { get; }
            public bool Manual { get; set; }
        }
        """;
}
