using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Wasp.IcCdk.SourceGenerator;

// Roslyn incremental source generator: scans the user's compilation for
// methods marked [CanisterQuery] / [CanisterUpdate] / [CanisterCompositeQuery]
// and emits, alongside each marked method, an [UnmanagedCallersOnly]
// thunk wrapper that:
//
//   1. Reads the candid-encoded message arg via Wasp.IcCdk.MessageContext
//   2. Decodes each parameter using Wasp.IcCdk.Candid.Reader
//   3. Calls the user's method
//   4. Encodes the return value via Wasp.IcCdk.Candid
//   5. Replies via Wasp.IcCdk.Reply
//
// The export name uses double-underscore separators
// (canister_<kind>__<methodname>); the build pipeline's icp-publish
// step rewrites these to the literal-space form the IC requires.

[Generator]
public sealed class CanisterEntryGenerator : IIncrementalGenerator
{
    private const string QueryAttr = "Wasp.IcCdk.CanisterQueryAttribute";
    private const string UpdateAttr = "Wasp.IcCdk.CanisterUpdateAttribute";
    private const string CompositeQueryAttr = "Wasp.IcCdk.CanisterCompositeQueryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(AttributeSource.Hint, AttributeSource.Source));

        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                transform: static (ctx, _) => Match(ctx))
            .Where(static m => m is not null);

        var combined = context.CompilationProvider.Combine(candidates.Collect());
        context.RegisterSourceOutput(combined, static (spc, source) => Emit(spc, source.Right!));
    }

    private static MatchedMethod? Match(GeneratorSyntaxContext ctx)
    {
        var methodSyntax = (MethodDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(methodSyntax) is not IMethodSymbol method) return null;

        string? kind = null;
        string? overrideName = null;
        bool manual = false;
        foreach (var attr in method.GetAttributes())
        {
            string fullName = attr.AttributeClass?.ToDisplayString() ?? "";
            kind = fullName switch
            {
                QueryAttr => "canister_query",
                UpdateAttr => "canister_update",
                CompositeQueryAttr => "canister_composite_query",
                _ => kind,
            };
            if (kind is not null)
            {
                if (attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is string s && s.Length > 0)
                {
                    overrideName = s;
                }
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key == "Manual" && named.Value.Value is bool b)
                    {
                        manual = b;
                    }
                }
                break;
            }
        }
        if (kind is null) return null;

        var containingType = method.ContainingType;
        if (containingType is null) return null;
        if (!IsValidContainer(containingType, methodSyntax)) return null;

        return new MatchedMethod(
            kind,
            overrideName ?? method.Name,
            manual,
            method,
            containingType,
            methodSyntax);
    }

    private static bool IsValidContainer(INamedTypeSymbol type, MethodDeclarationSyntax syntax)
    {
        // Container must be a non-generic, top-level or nested static partial class
        // so we can drop a generated partial alongside it without name conflicts.
        if (type.IsGenericType) return false;
        var parent = syntax.Parent as ClassDeclarationSyntax;
        if (parent is null) return false;
        if (!parent.Modifiers.Any(m => m.Text == "partial")) return false;
        return true;
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<MatchedMethod?> matches)
    {
        var byContainer = matches
            .Where(m => m is not null)
            .GroupBy(m => m!.Type, SymbolEqualityComparer.Default);

        foreach (var grp in byContainer)
        {
            var type = (INamedTypeSymbol)grp.Key!;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> emitted by Wasp.IcCdk.SourceGenerator");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Wasp.IcCdk;");
            sb.AppendLine();

            string? ns = type.ContainingNamespace.IsGlobalNamespace
                ? null
                : type.ContainingNamespace.ToDisplayString();
            if (ns is not null)
            {
                sb.Append("namespace ").Append(ns).AppendLine(";");
                sb.AppendLine();
            }

            sb.Append("partial class ").AppendLine(type.Name);
            sb.AppendLine("{");
            int idx = 0;
            foreach (var m in grp)
            {
                EmitThunk(sb, m!, idx++);
                sb.AppendLine();
            }
            sb.AppendLine("}");

            string fileName = (ns?.Replace('.', '_') ?? "_global") + "_" + type.Name + ".g.cs";
            spc.AddSource(fileName, sb.ToString());
        }
    }

    private static void EmitThunk(StringBuilder sb, MatchedMethod m, int index)
    {
        string export = $"{m.Kind}__{m.ExportName}";
        string thunkName = $"__WaspIcCdkThunk_{m.Kind.Replace("canister_", "")}_{m.ExportName}_{index}";
        var ret = m.Method.ReturnType;
        string retDisplay = ret.ToDisplayString();
        bool returnsVoid = retDisplay == "void";

        sb.Append("    [UnmanagedCallersOnly(EntryPoint = \"").Append(export).AppendLine("\")]");
        sb.Append("    public static void ").Append(thunkName).AppendLine("()");
        sb.AppendLine("    {");

        if (m.Manual)
        {
            // The user is responsible for arg decoding + replying. We just
            // forward through so the wasm export points at their method.
            sb.Append("        ").Append(m.Method.Name).AppendLine("();");
        }
        else
        {
            var parameters = m.Method.Parameters;
            if (parameters.Length > 0)
            {
                sb.AppendLine("        var __wasp_arg = MessageContext.ArgData();");
                sb.AppendLine("        var __wasp_reader = new Candid.Reader(__wasp_arg);");
                for (int i = 0; i < parameters.Length; i++)
                {
                    var p = parameters[i];
                    string read = ReaderCallFor(p.Type);
                    sb.Append("        var __wasp_p").Append(i).Append(" = __wasp_reader.").Append(read).AppendLine("();");
                }
            }

            sb.Append("        ");
            if (!returnsVoid) sb.Append("var __wasp_ret = ");
            sb.Append(m.Method.Name).Append("(");
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append("__wasp_p").Append(i);
            }
            sb.AppendLine(");");

            if (returnsVoid)
            {
                sb.AppendLine("        Reply.Empty();");
            }
            else
            {
                sb.Append("        Reply.Bytes(").Append(EncodeCallFor(ret)).Append("(__wasp_ret));");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
    }

    private static string ReaderCallFor(ITypeSymbol type) => type.SpecialType switch
    {
        SpecialType.System_Boolean => "ReadBool",
        SpecialType.System_UInt32 => "ReadNat32",
        SpecialType.System_UInt64 => "ReadNat64",
        SpecialType.System_Int32 => "ReadInt32",
        SpecialType.System_Int64 => "ReadInt64",
        SpecialType.System_String => "ReadText",
        _ when type.ToDisplayString() == "byte[]" => "ReadBlob",
        _ => throw new System.NotSupportedException($"Wasp.IcCdk Phase 1 source generator does not yet handle parameter type '{type.ToDisplayString()}'"),
    };

    private static string EncodeCallFor(ITypeSymbol type) => type.SpecialType switch
    {
        SpecialType.System_Boolean => "Candid.EncodeBool",
        SpecialType.System_UInt32 => "Candid.EncodeNat32",
        SpecialType.System_UInt64 => "Candid.EncodeNat64",
        SpecialType.System_Int32 => "Candid.EncodeInt32",
        SpecialType.System_Int64 => "Candid.EncodeInt64",
        SpecialType.System_String => "Candid.EncodeText",
        _ when type.ToDisplayString() == "byte[]" => "Candid.EncodeBlob",
        _ => throw new System.NotSupportedException($"Wasp.IcCdk Phase 1 source generator does not yet handle return type '{type.ToDisplayString()}'"),
    };

    private sealed class MatchedMethod
    {
        public MatchedMethod(string kind, string exportName, bool manual, IMethodSymbol method, INamedTypeSymbol type, MethodDeclarationSyntax syntax)
        {
            Kind = kind;
            ExportName = exportName;
            Manual = manual;
            Method = method;
            Type = type;
            Syntax = syntax;
        }
        public string Kind { get; }
        public string ExportName { get; }
        public bool Manual { get; }
        public IMethodSymbol Method { get; }
        public INamedTypeSymbol Type { get; }
        public MethodDeclarationSyntax Syntax { get; }
    }
}
